name = "steakflow"
main = "./.output/worker/index.js"
compatibility_date = "2024-05-01"

# Configure site assets
[site]
bucket = "./.output/static"

# Build command
[build]
command = "npm run build"
cwd = "."

# Environment variables
[vars]
NODE_ENV = "production"

# Production environment
[env.production]
workers_dev = true
routes = [
  { pattern = "*", zone_name = "steakflow.com" }
]

# Development environment
[env.development]
workers_dev = true

# Triggers
[triggers]
crons = []

# Miniflare configuration for local development
[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true