name = "steakflow"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

# Configure site assets
[site]
bucket = ".open-next/assets"

# Build command
[build]
command = "npm run build"
cwd = "."

# Environment variables
[vars]
NODE_ENV = "production"

# Assets binding
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Production environment
[env.production]
workers_dev = true
routes = [
  { pattern = "*", zone_name = "steakflow.com" }
]

# Development environment
[env.development]
workers_dev = true

# Triggers
[triggers]
crons = []

# Miniflare configuration for local development
[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true