name = "steakflow"
compatibility_date = "2024-02-20"

[site]
bucket = ".open-next/static"

[build]
command = "npm run build"

[env.production]
workers_dev = true

[[routes]]
pattern = "/*"
script_name = "worker" 